project:
  type: website
  output-dir: _site
  
website:
  title: "Killian Carroll"
  description: "Killian Carroll's personal academic website"
  site-url: "https://killian-carroll.github.io/"
  repo-url: "https://github.com/Killian-Carroll/killian-carroll.github.io"
  favicon: "images/favicon.ico"
  
  navbar:
    title: false
    background: primary
    foreground: light
    collapse-below: lg
    left:
      - text: "Home"
        href: index.qmd
      - text: "Research"
        href: research.qmd
    right:
      - icon: envelope
        href: "mailto:killian.carroll@fiscalcouncil.ie"
      - icon: linkedin
        href: https://ie.linkedin.com/in/killian-carroll-03207b120
      - icon: github
        href: https://github.com/killian-carroll
      - icon: twitter
        href: https://twitter.com/killiancarroll_
      - text: "{{< fa brands bluesky >}}" 
        href: https://bsky.app/profile/killiancarroll.bsky.social
      

  page-footer:
    left: |
      © 2025 Killian Carroll 
    right: |
      <div class="footer-logos">
        <a href="https://www.fiscalcouncil.ie/">
          ![Logo 1](images/logo.png){ style="height: 40px; margin-right: 20px;" }
        </a>
        <a href="https://www.ucd.ie/economics/">
          ![Logo 1](https://www.ucd.ie/economics/t4media/crest-ucd.svg){ style="height: 40px; margin-right: 20px;" }
        </a>
      </div>

format:
  html:
    theme: 
      light: [flatly, styles/flatly.scss]
      dark: [darkly, styles/darkly.scss]
    css: styles/stlyes.css
    toc: true
    code-tools: 
      source: false
      toggle: true
    code-fold: true
    code-summary: "Show code"
    highlight-style: a11y
    anchor-sections: false
    search: false
    
execute:
  freeze: auto